/*
由 Aqua Data Studio 9.0.13 于 三月-18-2013 10:53:13 上午
 日生成的脚本数据库：orcl
架构：PEIHAO
对象：TABLE
*/

CREATE TABLE JBPM4_DEPLOYMENT  ( 
	DBID_     	NUMBER(19,0) NOT NULL,
	NAME_     	CLOB NULL,
	TIMESTAMP_	NUMBER(19,0) NULL,
	STATE_    	VARCHAR2(255 CHAR) NULL,
	PRIMARY KEY(DBID_)
	NOT DEFERRABLE
	 VALIDATE
);
CREATE TABLE JBPM4_DEPLOYPROP  ( 
	DBID_      	NUMBER(19,0) NOT NULL,
	DEPLOYMENT_	NUMBER(19,0) NULL,
	OBJNAME_   	VARCHAR2(255 CHAR) NULL,
	KEY_       	VARCHAR2(255 CHAR) NULL,
	STRINGVAL_ 	VARCHAR2(255 CHAR) NULL,
	LONGVAL_   	NUMBER(19,0) NULL,
	PRIMARY KEY(DBID_)
	NOT DEFERRABLE
	 VALIDATE
);
CREATE TABLE JBPM4_EXECUTION  ( 
	DBID_         	NUMBER(19,0) NOT NULL,
	CLASS_        	VARCHAR2(255 CHAR) NOT NULL,
	DBVERSION_    	NUMBER(10,0) NOT NULL,
	ACTIVITYNAME_ 	VARCHAR2(255 CHAR) NULL,
	PROCDEFID_    	VARCHAR2(255 CHAR) NULL,
	HASVARS_      	NUMBER(1,0) NULL,
	NAME_         	VARCHAR2(255 CHAR) NULL,
	KEY_          	VARCHAR2(255 CHAR) NULL,
	ID_           	VARCHAR2(255 CHAR) NULL,
	STATE_        	VARCHAR2(255 CHAR) NULL,
	SUSPHISTSTATE_	VARCHAR2(255 CHAR) NULL,
	PRIORITY_     	NUMBER(10,0) NULL,
	HISACTINST_   	NUMBER(19,0) NULL,
	PARENT_       	NUMBER(19,0) NULL,
	INSTANCE_     	NUMBER(19,0) NULL,
	SUPEREXEC_    	NUMBER(19,0) NULL,
	SUBPROCINST_  	NUMBER(19,0) NULL,
	PARENT_IDX_   	NUMBER(10,0) NULL,
	PRIMARY KEY(DBID_)
	NOT DEFERRABLE
	 VALIDATE
);
CREATE TABLE JBPM4_HIST_ACTINST  ( 
	DBID_         	NUMBER(19,0) NOT NULL,
	CLASS_        	VARCHAR2(255 CHAR) NOT NULL,
	DBVERSION_    	NUMBER(10,0) NOT NULL,
	HPROCI_       	NUMBER(19,0) NULL,
	TYPE_         	VARCHAR2(255 CHAR) NULL,
	EXECUTION_    	VARCHAR2(255 CHAR) NULL,
	ACTIVITY_NAME_	VARCHAR2(255 CHAR) NULL,
	START_        	TIMESTAMP(6) NULL,
	END_          	TIMESTAMP(6) NULL,
	DURATION_     	NUMBER(19,0) NULL,
	TRANSITION_   	VARCHAR2(255 CHAR) NULL,
	NEXTIDX_      	NUMBER(10,0) NULL,
	HTASK_        	NUMBER(19,0) NULL,
	PRIMARY KEY(DBID_)
	NOT DEFERRABLE
	 VALIDATE
);
CREATE TABLE JBPM4_HIST_DETAIL  ( 
	DBID_      	NUMBER(19,0) NOT NULL,
	CLASS_     	VARCHAR2(255 CHAR) NOT NULL,
	DBVERSION_ 	NUMBER(10,0) NOT NULL,
	USERID_    	VARCHAR2(255 CHAR) NULL,
	TIME_      	TIMESTAMP(6) NULL,
	HPROCI_    	NUMBER(19,0) NULL,
	HPROCIIDX_ 	NUMBER(10,0) NULL,
	HACTI_     	NUMBER(19,0) NULL,
	HACTIIDX_  	NUMBER(10,0) NULL,
	HTASK_     	NUMBER(19,0) NULL,
	HTASKIDX_  	NUMBER(10,0) NULL,
	HVAR_      	NUMBER(19,0) NULL,
	HVARIDX_   	NUMBER(10,0) NULL,
	MESSAGE_   	CLOB NULL,
	OLD_STR_   	VARCHAR2(255 CHAR) NULL,
	NEW_STR_   	VARCHAR2(255 CHAR) NULL,
	OLD_INT_   	NUMBER(10,0) NULL,
	NEW_INT_   	NUMBER(10,0) NULL,
	OLD_TIME_  	TIMESTAMP(6) NULL,
	NEW_TIME_  	TIMESTAMP(6) NULL,
	PARENT_    	NUMBER(19,0) NULL,
	PARENT_IDX_	NUMBER(10,0) NULL,
	PRIMARY KEY(DBID_)
	NOT DEFERRABLE
	 VALIDATE
);
CREATE TABLE JBPM4_HIST_PROCINST  ( 
	DBID_       	NUMBER(19,0) NOT NULL,
	DBVERSION_  	NUMBER(10,0) NOT NULL,
	ID_         	VARCHAR2(255 CHAR) NULL,
	PROCDEFID_  	VARCHAR2(255 CHAR) NULL,
	KEY_        	VARCHAR2(255 CHAR) NULL,
	START_      	TIMESTAMP(6) NULL,
	END_        	TIMESTAMP(6) NULL,
	DURATION_   	NUMBER(19,0) NULL,
	STATE_      	VARCHAR2(255 CHAR) NULL,
	ENDACTIVITY_	VARCHAR2(255 CHAR) NULL,
	NEXTIDX_    	NUMBER(10,0) NULL,
	PRIMARY KEY(DBID_)
	NOT DEFERRABLE
	 VALIDATE
);
CREATE TABLE JBPM4_HIST_TASK  ( 
	DBID_     	NUMBER(19,0) NOT NULL,
	DBVERSION_	NUMBER(10,0) NOT NULL,
	EXECUTION_	VARCHAR2(255 CHAR) NULL,
	OUTCOME_  	VARCHAR2(255 CHAR) NULL,
	ASSIGNEE_ 	VARCHAR2(255 CHAR) NULL,
	PRIORITY_ 	NUMBER(10,0) NULL,
	STATE_    	VARCHAR2(255 CHAR) NULL,
	CREATE_   	TIMESTAMP(6) NULL,
	END_      	TIMESTAMP(6) NULL,
	DURATION_ 	NUMBER(19,0) NULL,
	NEXTIDX_  	NUMBER(10,0) NULL,
	SUPERTASK_	NUMBER(19,0) NULL,
	PRIMARY KEY(DBID_)
	NOT DEFERRABLE
	 VALIDATE
);
CREATE TABLE JBPM4_HIST_VAR  ( 
	DBID_       	NUMBER(19,0) NOT NULL,
	DBVERSION_  	NUMBER(10,0) NOT NULL,
	PROCINSTID_ 	VARCHAR2(255 CHAR) NULL,
	EXECUTIONID_	VARCHAR2(255 CHAR) NULL,
	VARNAME_    	VARCHAR2(255 CHAR) NULL,
	VALUE_      	VARCHAR2(255 CHAR) NULL,
	HPROCI_     	NUMBER(19,0) NULL,
	HTASK_      	NUMBER(19,0) NULL,
	PRIMARY KEY(DBID_)
	NOT DEFERRABLE
	 VALIDATE
);
CREATE TABLE JBPM4_ID_GROUP  ( 
	DBID_     	NUMBER(19,0) NOT NULL,
	DBVERSION_	NUMBER(10,0) NOT NULL,
	ID_       	VARCHAR2(255 CHAR) NULL,
	NAME_     	VARCHAR2(255 CHAR) NULL,
	TYPE_     	VARCHAR2(255 CHAR) NULL,
	PARENT_   	NUMBER(19,0) NULL,
	PRIMARY KEY(DBID_)
	NOT DEFERRABLE
	 VALIDATE
);
CREATE TABLE JBPM4_ID_MEMBERSHIP  ( 
	DBID_     	NUMBER(19,0) NOT NULL,
	DBVERSION_	NUMBER(10,0) NOT NULL,
	USER_     	NUMBER(19,0) NULL,
	GROUP_    	NUMBER(19,0) NULL,
	NAME_     	VARCHAR2(255 CHAR) NULL,
	PRIMARY KEY(DBID_)
	NOT DEFERRABLE
	 VALIDATE
);
CREATE TABLE JBPM4_ID_USER  ( 
	DBID_         	NUMBER(19,0) NOT NULL,
	DBVERSION_    	NUMBER(10,0) NOT NULL,
	ID_           	VARCHAR2(255 CHAR) NULL,
	PASSWORD_     	VARCHAR2(255 CHAR) NULL,
	GIVENNAME_    	VARCHAR2(255 CHAR) NULL,
	FAMILYNAME_   	VARCHAR2(255 CHAR) NULL,
	BUSINESSEMAIL_	VARCHAR2(255 CHAR) NULL,
	PRIMARY KEY(DBID_)
	NOT DEFERRABLE
	 VALIDATE
);
CREATE TABLE JBPM4_JOB  ( 
	DBID_           	NUMBER(19,0) NOT NULL,
	CLASS_          	VARCHAR2(255 CHAR) NOT NULL,
	DBVERSION_      	NUMBER(10,0) NOT NULL,
	DUEDATE_        	TIMESTAMP(6) NULL,
	STATE_          	VARCHAR2(255 CHAR) NULL,
	ISEXCLUSIVE_    	NUMBER(1,0) NULL,
	LOCKOWNER_      	VARCHAR2(255 CHAR) NULL,
	LOCKEXPTIME_    	TIMESTAMP(6) NULL,
	EXCEPTION_      	CLOB NULL,
	RETRIES_        	NUMBER(10,0) NULL,
	PROCESSINSTANCE_	NUMBER(19,0) NULL,
	EXECUTION_      	NUMBER(19,0) NULL,
	CFG_            	NUMBER(19,0) NULL,
	SIGNAL_         	VARCHAR2(255 CHAR) NULL,
	EVENT_          	VARCHAR2(255 CHAR) NULL,
	REPEAT_         	VARCHAR2(255 CHAR) NULL,
	PRIMARY KEY(DBID_)
	NOT DEFERRABLE
	 VALIDATE
);
CREATE TABLE JBPM4_LOB  ( 
	DBID_      	NUMBER(19,0) NOT NULL,
	DBVERSION_ 	NUMBER(10,0) NOT NULL,
	BLOB_VALUE_	BLOB NULL,
	DEPLOYMENT_	NUMBER(19,0) NULL,
	NAME_      	CLOB NULL,
	PRIMARY KEY(DBID_)
	NOT DEFERRABLE
	 VALIDATE
);
CREATE TABLE JBPM4_PARTICIPATION  ( 
	DBID_     	NUMBER(19,0) NOT NULL,
	DBVERSION_	NUMBER(10,0) NOT NULL,
	GROUPID_  	VARCHAR2(255 CHAR) NULL,
	USERID_   	VARCHAR2(255 CHAR) NULL,
	TYPE_     	VARCHAR2(255 CHAR) NULL,
	TASK_     	NUMBER(19,0) NULL,
	SWIMLANE_ 	NUMBER(19,0) NULL,
	PRIMARY KEY(DBID_)
	NOT DEFERRABLE
	 VALIDATE
);
CREATE TABLE JBPM4_PROPERTY  ( 
	KEY_    	VARCHAR2(255 CHAR) NOT NULL,
	VERSION_	NUMBER(10,0) NOT NULL,
	VALUE_  	VARCHAR2(255 CHAR) NULL,
	PRIMARY KEY(KEY_)
	NOT DEFERRABLE
	 VALIDATE
);
CREATE TABLE JBPM4_SWIMLANE  ( 
	DBID_     	NUMBER(19,0) NOT NULL,
	DBVERSION_	NUMBER(10,0) NOT NULL,
	NAME_     	VARCHAR2(255 CHAR) NULL,
	ASSIGNEE_ 	VARCHAR2(255 CHAR) NULL,
	EXECUTION_	NUMBER(19,0) NULL,
	PRIMARY KEY(DBID_)
	NOT DEFERRABLE
	 VALIDATE
);
CREATE TABLE JBPM4_TASK  ( 
	DBID_         	NUMBER(19,0) NOT NULL,
	CLASS_        	CHAR(1 CHAR) NOT NULL,
	DBVERSION_    	NUMBER(10,0) NOT NULL,
	NAME_         	VARCHAR2(255 CHAR) NULL,
	DESCR_        	CLOB NULL,
	STATE_        	VARCHAR2(255 CHAR) NULL,
	SUSPHISTSTATE_	VARCHAR2(255 CHAR) NULL,
	ASSIGNEE_     	VARCHAR2(255 CHAR) NULL,
	FORM_         	VARCHAR2(255 CHAR) NULL,
	PRIORITY_     	NUMBER(10,0) NULL,
	CREATE_       	TIMESTAMP(6) NULL,
	DUEDATE_      	TIMESTAMP(6) NULL,
	PROGRESS_     	NUMBER(10,0) NULL,
	SIGNALLING_   	NUMBER(1,0) NULL,
	EXECUTION_ID_ 	VARCHAR2(255 CHAR) NULL,
	ACTIVITY_NAME_	VARCHAR2(255 CHAR) NULL,
	HASVARS_      	NUMBER(1,0) NULL,
	SUPERTASK_    	NUMBER(19,0) NULL,
	EXECUTION_    	NUMBER(19,0) NULL,
	PROCINST_     	NUMBER(19,0) NULL,
	SWIMLANE_     	NUMBER(19,0) NULL,
	TASKDEFNAME_  	VARCHAR2(255 CHAR) NULL,
	PRIMARY KEY(DBID_)
	NOT DEFERRABLE
	 VALIDATE
);
CREATE TABLE JBPM4_VARIABLE  ( 
	DBID_        	NUMBER(19,0) NOT NULL,
	CLASS_       	VARCHAR2(255 CHAR) NOT NULL,
	DBVERSION_   	NUMBER(10,0) NOT NULL,
	KEY_         	VARCHAR2(255 CHAR) NULL,
	CONVERTER_   	VARCHAR2(255 CHAR) NULL,
	HIST_        	NUMBER(1,0) NULL,
	EXECUTION_   	NUMBER(19,0) NULL,
	TASK_        	NUMBER(19,0) NULL,
	LOB_         	NUMBER(19,0) NULL,
	DATE_VALUE_  	TIMESTAMP(6) NULL,
	DOUBLE_VALUE_	FLOAT NULL,
	CLASSNAME_   	VARCHAR2(255 CHAR) NULL,
	LONG_VALUE_  	NUMBER(19,0) NULL,
	STRING_VALUE_	VARCHAR2(255 CHAR) NULL,
	TEXT_VALUE_  	CLOB NULL,
	EXESYS_      	NUMBER(19,0) NULL,
	PRIMARY KEY(DBID_)
	NOT DEFERRABLE
	 VALIDATE
);

ALTER TABLE JBPM4_EXECUTION
	ADD ( UNIQUE (ID_)
	NOT DEFERRABLE INITIALLY IMMEDIATE VALIDATE );
ALTER TABLE JBPM4_DEPLOYPROP
	ADD ( CONSTRAINT FK_DEPLPROP_DEPL
	FOREIGN KEY(DEPLOYMENT_)
	REFERENCES JBPM4_DEPLOYMENT(DBID_)
	NOT DEFERRABLE INITIALLY IMMEDIATE VALIDATE );
ALTER TABLE JBPM4_EXECUTION
	ADD ( CONSTRAINT FK_EXEC_SUPEREXEC
	FOREIGN KEY(SUPEREXEC_)
	REFERENCES JBPM4_EXECUTION(DBID_)
	NOT DEFERRABLE INITIALLY IMMEDIATE VALIDATE );
ALTER TABLE JBPM4_EXECUTION
	ADD ( CONSTRAINT FK_EXEC_SUBPI
	FOREIGN KEY(SUBPROCINST_)
	REFERENCES JBPM4_EXECUTION(DBID_)
	NOT DEFERRABLE INITIALLY IMMEDIATE VALIDATE );
ALTER TABLE JBPM4_EXECUTION
	ADD ( CONSTRAINT FK_EXEC_PARENT
	FOREIGN KEY(PARENT_)
	REFERENCES JBPM4_EXECUTION(DBID_)
	NOT DEFERRABLE INITIALLY IMMEDIATE VALIDATE );
ALTER TABLE JBPM4_EXECUTION
	ADD ( CONSTRAINT FK_EXEC_INSTANCE
	FOREIGN KEY(INSTANCE_)
	REFERENCES JBPM4_EXECUTION(DBID_)
	NOT DEFERRABLE INITIALLY IMMEDIATE VALIDATE );
ALTER TABLE JBPM4_HIST_ACTINST
	ADD ( CONSTRAINT FK_HTI_HTASK
	FOREIGN KEY(HTASK_)
	REFERENCES JBPM4_HIST_TASK(DBID_)
	NOT DEFERRABLE INITIALLY IMMEDIATE VALIDATE );
ALTER TABLE JBPM4_HIST_ACTINST
	ADD ( CONSTRAINT FK_HACTI_HPROCI
	FOREIGN KEY(HPROCI_)
	REFERENCES JBPM4_HIST_PROCINST(DBID_)
	NOT DEFERRABLE INITIALLY IMMEDIATE VALIDATE );
ALTER TABLE JBPM4_HIST_DETAIL
	ADD ( CONSTRAINT FK_HDETAIL_HVAR
	FOREIGN KEY(HVAR_)
	REFERENCES JBPM4_HIST_VAR(DBID_)
	NOT DEFERRABLE INITIALLY IMMEDIATE VALIDATE );
ALTER TABLE JBPM4_HIST_DETAIL
	ADD ( CONSTRAINT FK_HDETAIL_HTASK
	FOREIGN KEY(HTASK_)
	REFERENCES JBPM4_HIST_TASK(DBID_)
	NOT DEFERRABLE INITIALLY IMMEDIATE VALIDATE );
ALTER TABLE JBPM4_HIST_DETAIL
	ADD ( CONSTRAINT FK_HDETAIL_HPROCI
	FOREIGN KEY(HPROCI_)
	REFERENCES JBPM4_HIST_PROCINST(DBID_)
	NOT DEFERRABLE INITIALLY IMMEDIATE VALIDATE );
ALTER TABLE JBPM4_HIST_DETAIL
	ADD ( CONSTRAINT FK_HDETAIL_HACTI
	FOREIGN KEY(HACTI_)
	REFERENCES JBPM4_HIST_ACTINST(DBID_)
	NOT DEFERRABLE INITIALLY IMMEDIATE VALIDATE );
ALTER TABLE JBPM4_HIST_TASK
	ADD ( CONSTRAINT FK_HSUPERT_SUB
	FOREIGN KEY(SUPERTASK_)
	REFERENCES JBPM4_HIST_TASK(DBID_)
	NOT DEFERRABLE INITIALLY IMMEDIATE VALIDATE );
ALTER TABLE JBPM4_HIST_VAR
	ADD ( CONSTRAINT FK_HVAR_HTASK
	FOREIGN KEY(HTASK_)
	REFERENCES JBPM4_HIST_TASK(DBID_)
	NOT DEFERRABLE INITIALLY IMMEDIATE VALIDATE );
ALTER TABLE JBPM4_HIST_VAR
	ADD ( CONSTRAINT FK_HVAR_HPROCI
	FOREIGN KEY(HPROCI_)
	REFERENCES JBPM4_HIST_PROCINST(DBID_)
	NOT DEFERRABLE INITIALLY IMMEDIATE VALIDATE );
ALTER TABLE JBPM4_ID_GROUP
	ADD ( CONSTRAINT FK_GROUP_PARENT
	FOREIGN KEY(PARENT_)
	REFERENCES JBPM4_ID_GROUP(DBID_)
	NOT DEFERRABLE INITIALLY IMMEDIATE VALIDATE );
ALTER TABLE JBPM4_ID_MEMBERSHIP
	ADD ( CONSTRAINT FK_MEM_USER
	FOREIGN KEY(USER_)
	REFERENCES JBPM4_ID_USER(DBID_)
	NOT DEFERRABLE INITIALLY IMMEDIATE VALIDATE );
ALTER TABLE JBPM4_ID_MEMBERSHIP
	ADD ( CONSTRAINT FK_MEM_GROUP
	FOREIGN KEY(GROUP_)
	REFERENCES JBPM4_ID_GROUP(DBID_)
	NOT DEFERRABLE INITIALLY IMMEDIATE VALIDATE );
ALTER TABLE JBPM4_JOB
	ADD ( CONSTRAINT FK_JOB_CFG
	FOREIGN KEY(CFG_)
	REFERENCES JBPM4_LOB(DBID_)
	NOT DEFERRABLE INITIALLY IMMEDIATE VALIDATE );
ALTER TABLE JBPM4_LOB
	ADD ( CONSTRAINT FK_LOB_DEPLOYMENT
	FOREIGN KEY(DEPLOYMENT_)
	REFERENCES JBPM4_DEPLOYMENT(DBID_)
	NOT DEFERRABLE INITIALLY IMMEDIATE VALIDATE );
ALTER TABLE JBPM4_PARTICIPATION
	ADD ( CONSTRAINT FK_PART_TASK
	FOREIGN KEY(TASK_)
	REFERENCES JBPM4_TASK(DBID_)
	NOT DEFERRABLE INITIALLY IMMEDIATE VALIDATE );
ALTER TABLE JBPM4_PARTICIPATION
	ADD ( CONSTRAINT FK_PART_SWIMLANE
	FOREIGN KEY(SWIMLANE_)
	REFERENCES JBPM4_SWIMLANE(DBID_)
	NOT DEFERRABLE INITIALLY IMMEDIATE VALIDATE );
ALTER TABLE JBPM4_SWIMLANE
	ADD ( CONSTRAINT FK_SWIMLANE_EXEC
	FOREIGN KEY(EXECUTION_)
	REFERENCES JBPM4_EXECUTION(DBID_)
	NOT DEFERRABLE INITIALLY IMMEDIATE VALIDATE );
ALTER TABLE JBPM4_TASK
	ADD ( CONSTRAINT FK_TASK_SWIML
	FOREIGN KEY(SWIMLANE_)
	REFERENCES JBPM4_SWIMLANE(DBID_)
	NOT DEFERRABLE INITIALLY IMMEDIATE VALIDATE );
ALTER TABLE JBPM4_TASK
	ADD ( CONSTRAINT FK_TASK_SUPERTASK
	FOREIGN KEY(SUPERTASK_)
	REFERENCES JBPM4_TASK(DBID_)
	NOT DEFERRABLE INITIALLY IMMEDIATE VALIDATE );
ALTER TABLE JBPM4_VARIABLE
	ADD ( CONSTRAINT FK_VAR_TASK
	FOREIGN KEY(TASK_)
	REFERENCES JBPM4_TASK(DBID_)
	NOT DEFERRABLE INITIALLY IMMEDIATE VALIDATE );
ALTER TABLE JBPM4_VARIABLE
	ADD ( CONSTRAINT FK_VAR_LOB
	FOREIGN KEY(LOB_)
	REFERENCES JBPM4_LOB(DBID_)
	NOT DEFERRABLE INITIALLY IMMEDIATE VALIDATE );
ALTER TABLE JBPM4_VARIABLE
	ADD ( CONSTRAINT FK_VAR_EXESYS
	FOREIGN KEY(EXESYS_)
	REFERENCES JBPM4_EXECUTION(DBID_)
	NOT DEFERRABLE INITIALLY IMMEDIATE VALIDATE );
ALTER TABLE JBPM4_VARIABLE
	ADD ( CONSTRAINT FK_VAR_EXECUTION
	FOREIGN KEY(EXECUTION_)
	REFERENCES JBPM4_EXECUTION(DBID_)
	NOT DEFERRABLE INITIALLY IMMEDIATE VALIDATE );
